os: osx

install:
  - wget -q https://github.com/fuse-open/fuse-studio/releases/download/1.9.0/fuse_osx_1_9_0.pkg -O fuse-installer.pkg && sudo installer -pkg fuse-installer.pkg -target /

jobs:
  include:
    - stage: build
      name: "Building DotNet"
      script: uno build TravisTest -tdotnet

    - stage: build 
      name: "Building Android"
      before_script:
        - printf '\ny' | fuse install android;
      script:
        - uno build TravisTest -tAndroid -n=-quiet

    - stage: build
      name: "Building iOS"
      osx_image: xcode9.4
      script:
        - uno build TravisTest -tios -DCOCOAPODS -n=-sdk -n=iphonesimulator -n=-quiet -n=CODE_SIGN_IDENTITY="" -n=CODE_SIGNING_REQUIRED=NO